server:
  port: 8999
  contextPath : /kafka
spring:
  application:
    name: kafka
  kafka:
    bootstrapServers: 10.0.23.241:9092
    consumer:
      groupId: myGroup
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      groupId: myGroup
      keyDeserializer: org.apache.kafka.common.serialization.StringSerializer
      valueDserializer: org.apache.kafka.common.serialization.StringSerializer
  topics: flight-events,
    flight-time-events,
    canceled-events,
    pax-events,
    flight-delay-events